{% set name = "Sophus" %}
{% set version = "1.24.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/strasdat/{{ name }}/archive/{{ version }}.tar.gz
  sha256: eb1da440e6250c5efc7637a0611a5b8888875ce6ac22bf7ff6b6769bbc958082

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [not win]
  host:
    - eigen >=3.4

  run:
    - eigen >=3.4

test:
  commands:
    - test -f ${PREFIX}/include/sophus/types.hpp                # [unix]
    - test -f ${PREFIX}/share/sophus/cmake/SophusTargets.cmake  # [unix]

about:
  home: https://github.com/strasdat/Sophus
  summary: C++ implementation of Lie Groups using Eigen
  description: |
    This is a c++ implementation of Lie groups commonly used for 2d and 3d
    geometric problems.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://strasdat.github.io/Sophus/
  dev_url: https://github.com/strasdat/Sophus

extra:
  recipe-maintainers:
    - versatran01
