{% set name = "Sophus" %}
{% set version = "22.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/strasdat/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 270709b83696da179447cf743357e36a8b9bc8eed5ff4b9d66d33fe691010bad

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
  host:
    - eigen >=3.3

  run:
    - eigen >=3.3

test:
  commands:
    - test -f ${PREFIX}/include/sophus/types.hpp                # [unix]
    - test -f ${PREFIX}/share/sophus/cmake/SophusTargets.cmake  # [unix]

about:
  home: https://github.com/strasdat/Sophus
  summary: C++ implementation of Lie Groups using Eigen
  description: |
    This is a c++ implementation of Lie groups commonly used for 2d and 3d
    geometric problems.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  doc_url: https://strasdat.github.io/Sophus/
  dev_url: https://github.com/strasdat/Sophus

extra:
  recipe-maintainers:
    - versatran01
